name: Publish VS Code Extension

on:
  # Auto publish when a release is published
  release:
    types: [ published ]

  # Manual publish through GitHub UI
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - pre-release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test
      continue-on-error: true # No tests yet

    - name: Lint code
      run: npm run lint
      continue-on-error: true # No linter yet

    - name: Compile TypeScript
      run: npm run compile

    - name: Install VSCE
      run: npm install -g @vscode/vsce

    - name: Update version (manual dispatch)
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ "${{ github.event.inputs.release_type }}" = "pre-release" ]; then
          npm version prerelease --preid=beta
        else
          npm version ${{ github.event.inputs.release_type }}
        fi
        git push origin main --tags

    - name: Package extension
      run: vsce package

    - name: Publish to VS Code Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        if [ "${{ github.event.inputs.release_type }}" = "pre-release" ] || [[ "${{ github.ref }}" == *"beta"* ]] || [[ "${{ github.ref }}" == *"alpha"* ]]; then
          vsce publish --pre-release
        else
          vsce publish
        fi

    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: mdx-toolkit-${{ github.run_number }}.vsix
        path: "*.vsix"

    - name: Create GitHub Release (manual dispatch)
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        body: |
          ## Changes
          - Automated release via GitHub Actions

          ## Installation
          Download the `.vsix` file and install it manually, or install from the VS Code Marketplace.
        files: "*.vsix"
        draft: false
        prerelease: ${{ github.event.inputs.release_type == 'pre-release' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_VERSION: ${{ steps.version.outputs.new_version }}
